services:
  - type: web
    name: portman
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
      php artisan migrate --force  # Optional: Auto-run migrations
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    phpVersion: 8.2
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d217423uibrs73edi39g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: portman_db_3s7g
      - key: DB_USERNAME
        value: portman_db_3s7g_user
      - key: DB_PASSWORD
        value: cf6TRCC3KMuR0LhmGvSsiDhkuZxVRz73